### ISSUE TITLE
Failed to activate the scp package

### ISSUE THREAD

**Issue by ostapyrih** [mduvall/scp#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [scp](https://github.com/mduvall/scp) package, v0.1.0
### Stack Trace

Failed to activate the scp package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (file:///C:/Users/Ostap/.atom/packages/scp/lib/scp.coffee:11:23)
    at Package.module.exports.Package.activateNow (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:170:19)
    at C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:92:15)
    at C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:512:21)
    at C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (C:\Users\Ostap\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -0:43.6.0 command-palette:toggle (atom-pane.pane.active)
     -0:38.1.0 settings-view:view-installed-packages (atom-pane.pane.active)
  2x -0:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
browser-plus, v0.0.54
scp, v0.1.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by cyril851122** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [scp](https://github.com/mduvall/scp) package 0.1.0


### Stack Trace

Failed to activate the scp package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/scp/lib/scp.coffee:11:23)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.7.3 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
duotone-light-syntax 2.1.0 
intentions 1.1.2 
linter 2.1.2 
linter-python 3.1.1 
linter-ui-default 1.2.2 
scp 0.1.0 
```

**Comment by wojtekadams** [comment]
Reproduced on Ubuntu and Atom  1.60.0
